//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BorrowBookDetails = new HashSet<BorrowBookDetail>();
            this.ReturnBooks = new HashSet<ReturnBook>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string BookImage { get; set; }
        public string Description { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int PublicsherID { get; set; }
        public int CategoryID { get; set; }
        public int AuthorID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowBookDetail> BorrowBookDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnBook> ReturnBooks { get; set; }
    }
}
